#!/usr/bin/env bash

set -e

repo="trycanal/cli"
output_tgz="/tmp/canal.tgz"
dest_binary="/usr/local/bin"
os=$(uname | tr '[:upper:]' '[:lower:]')

echo "Downloading Canal CLI archive..."

latest_tag=$(curl --silent "https://api.github.com/repos/$repo/releases/latest" | grep '"tag_name":' | sed -E 's/.*"([^"]+)".*/\1/')
version=$(echo $latest_tag | sed 's/^v//')

test -f $output_tgz && rm -f $output_tgz
curl -o $output_tgz -sOL "https://github.com/${repo}/releases/download/${latest_tag}/cli_${version}_${os}_amd64.tar.gz"

echo "Uncompressing Canal binary in $dest_binary directory..."
tar -xzf $output_tgz -C $dest_binary
rm -f $output_tgz

echo -e "\nCanal CLI has been installed!"